{
    "openapi":"3.0.0",
    "info": {
        "title": "Viva Vaga Api",
        "description": "Api para gerenciar estacionamentos, definir valores e tempos de veículos nas vagas, registrar entrada e saída de veículos com nomes de clientes e proprietários de estacionamentos",
        "termsOfService": "",
        "contact": {
            "email": "joaovictorsal777@gmail.com"
        },
        "version":"1.0.0"
    },
    "servers": [
        {
            "url": "http://localhost:3000/",
            "description": "API Test"
        }
    ],
    "paths": {
        "/users": {
            "post":{
                "summary":"Cadastro de usuários",
                "description": "Rota de criação de usuários",
                "tags":["Users"],
                "requestBody": {
                    "content": {
                        "application/json":{
                            "schema": {
                                "$ref": "#/components/schemas/Users"
                            },
                            "examples": {
                                "user": {
                                    "value": {
                                        "name": "Rick",
                                        "lastname": "Grimes",
                                        "email": "rick.grimes@email.com",
                                        "password": "rick1234"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "400": {
                        "description": "Email indísponivel"
                    },
                    "201": {
                        "description": "Cadastro concluído"
                    }
                }
            }
        },
        "/users/all": {
            "get": {
                "summary": "Busca de usuários",
                "description": "Busca de todos usuários com query",
                "tags": ["Users"],
                "security": [{ "bearerAuth": [] }],
                "parameters": [
                    {
                        "name": "order",
                        "in": "query",
                        "description": "Ordem da listagem de usuários",
                        "require": false
                    },
                    {
                        "name": "sort",
                        "in": "query",
                        "description": "Coluna de ordem de busca",
                        "require": false
                    },
                    {
                        "name": "page",
                        "in": "query",
                        "description": "Pagina de listagem de usuários",
                        "require": false
                    },
                    {
                        "name": "perPage",
                        "in": "query",
                        "description": "Número de resultados por página",
                        "require": false
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/Users"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Usuário não autorizado"
                    },
                    "204": {
                        "description": "Nenhum usuário encontrado"
                    }
                }
            }
        },
        "/users/{id}": {
            "get": {
                "summary": "Busca de usuário por id",
                "description": "Busca de usuário a partir do id",
                "tags": ["Users"],
                "security": [{ "bearerAuth": [] }],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "Busca pelo o usuário pelo o path",
                        "require": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref":"#/components/schemas/Users"
                                },
                                "examples": {
                                    "user": {
                                        "value": {
                                            "name": "Rick",
                                            "lastname": "Grimes",
                                            "email": "rick.grimes@email.com"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Usuário não utorizado"
                    },
                    "204": {
                        "description": "Usuário não encontrado"
                    }
                }
            }
        },
        "/users/edit/{id}": {
            "put": {
                "summary": "Edição de dados do usuário",
                "description": "Editar dados do usuário",
                "tags": ["Users"],
                "security": [{ "bearerAuth": [] }],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "$ref": "#/components/schemas/Users"
                            },
                            "examples": {
                                "user": {
                                    "value": {
                                        "name":"Rick",
                                        "lastname": "Grimes Reg",
                                        "email":"rick.grimes2023@email.com"
                                    }
                                }
                            }
                        }
                    }
                },
                "parameters": [
                    {
                        "name": "id",
                        "in":"path",
                        "description": "Edição do usuário a partir do id do usuário",
                        "require": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref":"#/components/schemas/Users"
                                }
                            }
                        }
                    },
                    "401": {
                        "description":"Usuário não autorizado"
                    },
                    "400": {
                        "description": "Email indísponivel"
                    }
                }
            }
        },
        "/users/delete/{id}": {
            "delete": {
                "summary": "Deletar Usuário",
                "description": "Rota de exclusão de conta do usuário",
                "tags": ["Users"],
                "security": [{ "bearerAuth": [] }],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description":"Busca pelo o usuário pelo o path",
                        "require": "true"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Usuário deletado"
                    },
                    "401": {
                        "description":"Usuário não utorizado"
                    },
                    "400": {
                        "description":"Nenhum usuário encontrado"
                    }
                }
            }
        },
        "/companies" :{
            "post": {
                "summary": "Criar Empresa",
                "description": "Rota de criação de empresas",
                "tags": ["Companies"],
                "security": [{ "bearerAuth": [] }],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type":"object",
                                "$ref":"#/components/schemas/Companies"
                            },
                            "examples": {
                                "Companies": {
                                    "value": {
                                        "name": "Parking Vagas",
                                        "price_per_hour": 3.50,
                                        "city": "João Pessoa",
                                        "state": "Paraíba"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Created",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type":"object",
                                    "$ref":"#/components/schemas/Companies"
                                },
                                "examples": {
                                    "Companies": {
                                        "value": {
                                            "name": "Parking Vagas",
                                            "city":"João Pessoa",
                                            "state":"Paraíba",
                                            "price_per_hour": 3.99,
                                            "company_owner": {
                                                "name": "Rick",
                                                "lastname":"Grimes",
                                                "email": "rick.grimes@email.com"
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }

        },
        "/companies/all" : {
            "get": {
                "summary": "Buscar empresas",
                "description": "Faz a busca de todas as empresas",
                "tags": ["Companies"],
                "security": [{ "bearerAuth": [] }],
                "parameters": [
                    {
                        "name": "order",
                        "in": "query",
                        "description": "Ordenar busca decrescente ou crescente(só será válido se a buscar estive com o parametro sort junto)",
                        "require": false
                    },
                    {
                        "name":"sort",
                        "in": "query",
                        "description": "Indicar por qual coluna deve ser ordernar(Só será válido se o order estiver junto)",
                        "require": false
                    },
                    {
                        "name":"page",
                        "in": "query",
                        "description":"Pagina de listagem de Empresas",
                        "require": false
                    },
                    {
                        "name":"perPage",
                        "in":"query",
                        "description":"Número de resultados por página",
                        "require": false
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                           "application/json": {
                            "schema": {
                                "type":"object",
                                "$ref":"#/components/schemas/Companies"
                            }
                           }
                        }
                    },
                    "401": {
                        "description":"Usuário não autorizado"
                    },
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/companies/{id}" : {
            "get": {
                "summary":"Busca de empresa por id",
                "description": "Busca uma empresa a partir de um id",
                "tags": ["Companies"],
                "security": [{ "bearerAuth": [] }],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "Id da empresa",
                        "require": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type":"object",
                                    "$ref":"#/components/schemas/Companies"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Usuário não autorizado"
                    },
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/companies/owner": {
            "get": {
                "summary": "Busca de empresa a partir do propriétario",
                "description": "Faz a busca da empresa a partir do usuário logado",
                "tags": ["Companies"],
                "security": [{ "bearerAuth": [] }],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type":"object",
                                    "$ref":"#/components/schemas/Companies"
                                }
                            }
                        }
                    },
                    "401": {
                        "description":"Usuário não utorizado"
                    },
                    "204": {
                        "description":"No Content"
                    }
                }
            }
        },
        "/companies/edit/{id}" : {
            "put": {
                "summary": "Editar empresa",
                "description": "Edicão de dados da empresa",
                "tags": ["Companies"],
                "security": [{ "bearerAuth": [] }],
                "parameters": [
                    {
                        "name":"id",
                        "in": "path",
                        "description": "Id da empresa a ser editada",
                        "require": true
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type":"object",
                                "$ref":"#/components/schemas/Companies"
                            },
                            "examples": {
                                "Companies": {
                                    "value": {
                                        "name": "Parking Vagas",
                                        "city":"João Pessoa",
                                        "state":"Paraíba",
                                        "price_per_hour": 3.99
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/Companies"
                                },
                                "examples": {
                                    "Companies": {
                                        "value": {
                                            "name": "Parking Vagas",
                                            "city":"João Pessoa",
                                            "state":"Paraíba",
                                            "price_per_hour": 3.99,
                                            "company_owner": {
                                                "name": "Rick",
                                                "lastname":"Grimes",
                                                "email": "rick.grimes@email.com"
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "401": {
                        "description":"Usuário não utorizado"
                    }
                }
            }
        },
        "/companies/delete/{id}": {
            "delete": {
                "summary": "Deletar Empresa",
                "description": "Exclusão da empresa a partir do id",
                "tags": ["Companies"],
                "security": [{ "bearerAuth": [] }],
                "parameters": [
                    {
                        "name": "id",
                        "in":"path",
                        "description":"Id da empresa a ser deletada",
                        "require": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Empresa deletada"
                    },
                    "401": {
                        "description":"Usuário não autorizado"
                    },
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/login": {
            "post": {
                "summary": "Login no sistema",
                "description": "Rota responsavel por fazer login no sistema",
                "tags": ["Login"],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type":"object",
                                "$ref":"#/components/schemas/Companies"
                            },
                            "examples": {
                                "login": {
                                    "value": {
                                        "email": "rick.grimes@email.com",
                                        "password":"rick1234"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref":"#/components/schemas/Token"
                                },
                                "examples": {
                                    "Token": {
                                        "value": {
                                            "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Email ou senha incorretos"
                    }
                }
            }
        },
        "/lots/create/{id}": {
            "post": {
                "summary": "Criar novo registro de estacionamento",
                "description": "Criação de um novo registro de estacionamento vinculado a uma empresa",
                "tags": ["Lots"],
                "security": [{ "bearerAuth": [] }],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "$ref": "#/components/schemas/Lots"
                            },
                            "examples": {
                                "Lots": {
                                    "value": {
                                        "client": "Antonio",
                                        "plate": "ESSD-1332",
                                        "type_vehicle": "Carro"
                                    }
                                }
                            }
                        }
                    }
                },
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "Id da empresa",
                        "require": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref":"#/components/schemas/Lots"
                                },
                                "examples": {
                                    "Lots": {
                                        "value": {
                                            "client": "Antonio",
                                            "plate": "ESSD-1332",
                                            "type_vehicle": "Carro",
                                            "price": 3.99,
                                            "status": "Active",
                                            "company_lot": {
                                                "name": "Parking Vagas",
                                                "price_per_hour": 3.99
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "401": {
                        "description":"Usuário não Autorizado"
                    }
                }
            }
        },
        "/lots/company/{id}" : {
            "get": {
                "summary": "Busca de registros de estacionamento",
                "description": "Busca registros de estacionamentos associados a uma empresa",
                "tags": ["Lots"],
                "security": [{ "bearerAuth": [] }],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "Id da empresa",
                        "require": true
                    },
                    {
                        "name": "order",
                        "in": "query",
                        "description": "Ordem da listagem de usuários",
                        "require": false
                    },
                    {
                        "name": "sort",
                        "in": "query",
                        "description": "Coluna de ordem de busca",
                        "require": false
                    },
                    {
                        "name": "page",
                        "in": "query",
                        "description": "Pagina de listagem de usuários",
                        "require": false
                    },
                    {
                        "name": "perPage",
                        "in": "query",
                        "description": "Número de resultados por página",
                        "require": false
                    },
                    {
                        "name": "search",
                        "in": "query",
                        "description": "Busca pelo nome do cliente nos registros de estacionamento da empresa indicada no id"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/Lots"
                                },
                                "examples": {
                                    "Lots": {
                                        "value": {
                                            "client": "Antonio",
                                            "plate": "ESSD-1332",
                                            "type_vehicle": "Carro",
                                            "price": 3.99,
                                            "status": "Active",
                                            "company_lot": {
                                                "name": "Parking Vagas",
                                                "price_per_hour": 3.99
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Usuário não autorizado"
                    },
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/lots/{id}": {
            "get": {
                "summary": "Busca registro por id",
                "description": "Busca um registro por id indicado",
                "tags": ["Lots"],
                "security": [{ "bearerAuth": [] }],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "id do registro de estacionamento",
                        "require": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type":"object",
                                    "$ref":"#/components/schemas/Lots"
                                },
                                "examples": {
                                    "Lots": {
                                        "value": {
                                            "client": "Antonio",
                                            "plate": "ESSD-1332",
                                            "type_vehicle": "Carro",
                                            "price": 3.99,
                                            "status": "Active",
                                            "company_lot": {
                                                "name": "Parking Vagas",
                                                "price_per_hour": 3.99
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Usuário não Autorizado"
                    },
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/lots/edit/{id}": {
            "put": {
                "summary": "Editar registro de estacionamento",
                "description": "Editar dados de um registro de estacionamento a partir do id",
                "tags": ["Lots"],
                "security": [{ "bearerAuth": [] }],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "$ref":"#/components/schemas/Lots"
                            },
                            "examples": {
                                "Lots": {
                                    "value": {
                                        "client": "Antonio",
                                        "plate": "ESSD-1332",
                                        "type_vehicle": "Carro"
                                    }
                                }
                            }
                        }
                    }
                },
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "Id do registro de estacionamento",
                        "require": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type":"object",
                                    "$ref":"#/components/schemas/Lots"
                                },
                                "examples": {
                                    "Lots": {
                                        "value": {
                                            "client": "Antonio",
                                            "plate": "ESSD-1332",
                                            "type_vehicle": "Carro",
                                            "price": 3.99,
                                            "status": "Active",
                                            "company_lot": {
                                                "name": "Parking Vagas",
                                                "price_per_hour": 3.99
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Usuário não Autorizado"
                    },
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/lots/close/{id}": {
            "put": {
                "summary": "Encerrar estacionamento",
                "description": "Essa rota é para encerrar o estacionamento, ela vai contar o numero de horas gastas e multiplicar pelo o valor da hora da empresa e retornar o valor total à pagar no estacioanmento",
                "tags": ["Lots"],
                "security": [{ "bearerAuth": [] }],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type":"object",
                                "$ref":"#/components/schemas/Lots"
                            },
                            "examples": {
                                "Lots": {
                                    "value": {
                                        "status": "closed"
                                    }
                                }
                            }
                        }
                    }
                },
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "id do registro de estacionamento",
                        "require": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type":"object",
                                    "$ref":"#/components/schemas/Lots"
                                },
                                "examples": {
                                    "Lots": {
                                        "value": {
                                            "client": "Antonio",
                                            "plate": "ESSD-1332",
                                            "type_vehicle": "Carro",
                                            "price": 12.90,
                                            "status": "Closed",
                                            "company_lot": {
                                                "name": "Parking Vagas",
                                                "price_per_hour": 3.99
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Usuário não Autorizado"
                    },
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        }

    },
    "components": {
        "schemas" : {
            "Users": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "lastname": {
                        "type": "string"
                    },
                    "email": {
                        "type": "string"
                    },
                    "password": {
                        "type": "string"
                    },
                    "id": {
                        "type": "string"
                    }
                }
            },
            "Token": {
                "type": "object",
                "properties": {
                    "token": {
                        "type": "string"
                    }
                }
            },
            "Companies": {
                "type": "object",
                "properties": {
                    "name": {
                        "type":"string"
                    },
                    "price_per_hour": {
                        "type": "number"
                    },
                    "city": {
                        "type":"string"
                    },
                    "state": {
                        "type": "string"
                    },
                    "owner": {
                        "type": "string"
                    },
                    "company_owner": {
                        "type": "object"
                    },
                    "id": {
                        "type": "string"
                    }
                }
            },
            "Lots": {
                "type": "object",
                "properties": {
                    "client": {
                        "type": "string"
                    },
                    "plate": {
                        "type": "string"
                    },
                    "type_vehicle": {
                        "type": "string"
                    },
                    "price": {
                        "type": "number"                        
                    },
                    "status": {
                        "type": "string"
                    },
                    "id": {
                        "type": "string"
                    },
                    "company_lot": {
                        "type":"object"
                    }
                }
            }
        },
        "securitySchemes": {
            "bearerAuth": {
                "type": "http",
                "scheme": "bearer",
                "bearerFormat": "JWT"
            }
        }
    }
}